KST_TZ = "Asia/Seoul"

MIN_CHARS = 700
MAX_CHARS = 1000
MIN_ITEMS = 3
MAX_ITEMS = 5
MIN_SENTENCES = 2
MAX_SENTENCES = 4
MIN_SOURCES_TOTAL = 4
MAX_SINGLE_SOURCE_RATIO = 0.5

FORBIDDEN_WORDS = ["충격", "대박", "속보", "확정 수익"]

DEFAULT_AUTHOR = "AIBC Desk"
DEFAULT_CATEGORY = "News"
